language: c
sudo: required

os:
  - linux
  - osx

compiler:
  - gcc

branches:
  only:
    - master

# Install dependencies for various OS'
before_install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install make cmake; fi
  - if [ $TRAVIS_OS_NAME = linux ];   then sudo apt-get purge cmake && sudo apt-key update && sudo apt-get update && sudo apt-get -y -f install gfortran libz-dev m4 bison python3 cmake; fi
  - if [ $TRAVIS_OS_NAME = osx ];     then xcode-select --install && brew update && brew install gcc; fi
  - export FC=$(which gfortran);      echo $FC
  - export CC=$(which gcc);           echo $CC
  - export CXX=$(which g++);          echo $CXX

install:
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - DEPS_DIR="${HOME}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  # Exodus requires CMAKE 1.10.X+, which apt-get doesn't serve
  # Manually build
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cd -
  - cmake --version
  ############################################################################
  # Build PETSc from source
  ############################################################################
  - cd ${DEPS_DIR}
  - git clone https://gitlab.com/petsc/petsc.git petsc && cd petsc
  - git checkout xsdk-0.2.0
  - ./configure --download-mpich=yes --download-metis=yes --download-parmetis=yes --download-fblaslapack=1
  - export PETSC_DIR=$(pwd) && export PETSC_ARCH=arch-linux2-c-debug
  - echo "PETSC_DIR = $PETSC_DIR"
  - if [ $TRAVIS_OS_NAME = osx ]; then export PETSC_ARCH=arch-darwin-c-debug; fi
  - make PETSC_DIR=$PETSC_DIR PETSC_ARCH=$PETSC_ARCH all
  - cd -
  ############################################################################
  # Build HDF5 from source
  ############################################################################
  - cd ${DEPS_DIR}
  - wget https://support.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.10.5.tar.gz
  - cd hdf5-1.10.5 && export HDF5_DIR=$(pwd)
  - ./configure --prefix=${HDF5_DIR} --enable-fortran
  - make && make install
  - cd -
  ############################################################################
  # Get LaGriT
  ############################################################################
  - cd ${DEPS_DIR}
  - git clone https://github.com/lanl/LaGriT.git LaGriT
  - export LAGRIT_DIR=$(pwd)/LaGriT/
  - cd -

script:
  - make lglibs
  - make voronoi
  - make test

